### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by jayvdb** [spulec/django-file-keeper#1]
Would you mind clarifying the licensing please.

It is really helpful to have a LICENSE file in the repository - without that it is unclear , and the license text usually refers to a Copyright line which is contained in that file, and is custom for each project.

**Comment by spulec** [comment]
Thanks. Added Apache-2 with https://github.com/spulec/django-file-keeper/commit/5b7fe025748ae2873f2372e90407547d4865bed0

I should warn that I haven't used this library since 2013 so I am guessing it will not work properly with recent versions of Django.

**Comment by jayvdb** [comment]
Thanks

And re the warning, https://github.com/pakal/django-compat-patcher to the rescue ;-)
